### ISSUE TITLE
FR: rebase for newer kernels

### ISSUE THREAD

**Issue by tim77** [hakavlad/le9-patch#2]
Title. Actual kernel version is 5.9. Would be nice to rebase current patches for new kernels.

**Comment by hakavlad** [comment]
https://github.com/hakavlad/le9-patch/blob/main/le9g-5.9.patch

**Comment by hakavlad** [comment]
le9g is simplest patch. Need to rebase le9h.

**Comment by tim77** [comment]
Thanks. Unfortunately no luck for me on Fedora 33 at this moment. Quick and dirty .spec here https://copr.fedorainfracloud.org/coprs/atim/kernel-le9/

**Comment by hakavlad** [comment]
Will you try to fix this?
